### ISSUE TITLE
[Feature Request] i need 0('N')-1('Y') with one bubble... is it possible?

### ISSUE THREAD

**Issue by ibrahimkilic** [Udayraj123/OMRChecker#61]
I want 'yes' when bubble is full and 'no' when empty, in result csv file.... is it posible?
![example](https://user-images.githubusercontent.com/10168961/193658401-66b83995-b915-4e81-a961-457ce7ad0604.jpg)

**Comment by Udayraj123** [comment]
@ibrahimkilic We can introduce a new config in template.json for defining what to use for empty value. 
I have asked in the community for anyone who can pick it up. We can discuss what should the schema be for most generalised version. 

p.s. previously there was a variable used for this. Had to remove it because it would cause some issues in double-integer type questions.

**Comment by Udayraj123** [comment]
For now I can suggest a small hack in the [code here](https://github.com/Udayraj123/OMRChecker/blob/5e4985f/src/utils/imgutils.py#L912).

Add an `else` block there and put this(with correct indentation)
```
else:
    if (q in ["q1", "q2", "q3", "q4", "q5"]):
        omr_response[q] = "no"
```

**Comment by sanmay321** [comment]
@ibrahimkilic hey I would like to work on this issue assign me, please.

**Comment by Udayraj123** [comment]
@sanmay321 we're following a process of discussing on discord before getting assigned. Please start a discussion over there :)

**Comment by Udayraj123** [comment]
let's discuss how to generalize

**Comment by ibrahimkilic** [comment]
Thanks, bro...
